### ISSUE TITLE
Extension installation issues

### ISSUE THREAD

**Issue by rohitfarmer** [schochastics/quarto-social-share#4]
Hi there. Thank you for providing this extension. I am trying to install it for my blog; however, I am getting the following error. I think it has something to do with the SSL certificates. 

```
ERROR: TypeError: error sending request for url (https://codeload.github.com/schochastics/quarto-social-share/tar.gz/refs/heads/main#undefined): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```
How can I resolve this issue? I am on a Mac. Thanks!

**Comment by schochastics** [comment]
Hmm hard to say. I feel like this is not an issue that comes from the extension (just tried to install myself).  I will investigate though

**Comment by rohitfarmer** [comment]
So, I cloned the repo first and then did a local install by `quarto install extension quarto-social-share`. It worked! However, when I included it in the YAML header of my post, the share buttons were at the very bottom of the page, even below the footer. I expected it to be at the bottom of the post above the comments section. Is there any setting that I can tweak?

```
---
title: "Data Transformation"
description: "Data transformation is a process of performing a mathematical function on each data point used in a statistical or machine learning analysis to either satisfy the underlying assumptions, help a machine-learning algorithm to converge faster and or make a visualization interpretable."
author: 
  - name: "Rohit Farmer"
    orcid: "0000-0003-4197-3047"
date: "2022-10-05"
categories: [Concepts, Data Transformation]
format:
  html:
    code-fold: true
    code-tools: true
filters:
  - social-share
share:
  permalink: "https://dataalltheway.com/posts/001-data-transformation/"
  description: "Data Transformation"
  twitter: true
  facebook: true
  reddit: true
  linkedin: true
  email: true
---
```
